INSERT INTO ACTIVE_CHAT (id, CHAT_ID) VALUES (1, '1001L');
INSERT INTO INCOME (id, CHAT_ID, INCOMES) VALUES (1, '1001L', 99);
INSERT INTO SPEND (id, CHAT_ID, SPEND) VALUES (1, '1001L', 575);
SELECT * FROM ACTIVE_CHAT;
SELECT * FROM INCOME;
SELECT * FROM SPEND;